name: Build Run and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8
    - name: Build test
      run: mvn test
    - name: Build and Generate coverage
      run: mvn test jacoco:report
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 1
    - name: Build main
      run: mvn compile exec:java -Dexec.mainClass="streambms.BMSPublisher"
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Build main
      with:
       python-version: '3.9'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install pyinstaller
    - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
    - name: Pipe run
      run: ./SenderExec | python ./Reciver/receive.py
